### ISSUE TITLE
I got a question while working on a local file in Korean.

### ISSUE THREAD

**Issue by labrie75** [bjakja/Kainote#377]
1.Dwukrotnym kliknięciu linii (zawsze włączone)
2.Każdej zmianie linii
3.Kliknięciu linii lub edycji na pauzie
4.Kliknięciu linii lub edycji
5.Edycji na pauzie
6.Edycji

I'm not sure what the explanation above means.

I understand number one and two.

Number three and four are the same moves.
Number 5 and 6 are the same moves. 
What's the difference?

I don't understand the way it works, so it doesn't translate well.

![image](https://user-images.githubusercontent.com/82786635/116513005-e4968d80-a903-11eb-99df-9d31b10a2a62.png)

**Comment by bjakja** [comment]
It was an old options, I thought about removing it. anyway, 3 = click on line and edition when video is paused.
4 = click on line and edition even when video is played, change video position to start time of  when played. Unwanted for me but one person request it on start of making this program because video before have that bug and he like it in way like that.
5 is the same as 3 but without click on line, 6 the same as 4 but without click on line.
Anyway, I don't know if someone uses it now. I using double click.

**Comment by labrie75** [comment]
All right.
I don't think it's a necessary function.
However, there is nothing I can do about it because some people say it is bitter.
The function is not understandable to translate into Korean.
I'll just leave it out and translate it appropriately.
